services:
  mongo:
    image: mongo:8.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - momento

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION_NAME: eu-central-1
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - momento

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8088:8088"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    networks:
      - momento

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    volumes:
      - ./minio-init:/scripts
    entrypoint: ["/bin/sh", "-c", "chmod +x /scripts/create-bucket.sh && sleep 5 && /scripts/create-bucket.sh"]
    networks:
      - momento


volumes:
  minio-data:
  mongo-data:

networks:
  momento:
    driver: bridge